server:
  port: 8080
spring:
  datasource:
    druid:
      username: root
      password: flzx_3qc
      url: jdbc:mysql://localhost:3308/myblog?useSSL=true&serverTimezone=Asia/Shanghai&useUnicode=true&charsetEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      min-idle: 5
      max-wait: 60000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  redis:
    database: 15
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000



#    schema: classpath:/database/schema/article-schema.sql
#    data: classpath:/database/data/article.sql
#    initialization-mode: always

mybatis:
  mapper-locations: classpath:/mappings/*.xml
  type-aliases-package: com.athome.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true


#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: info
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions
